#!/usr/bin/env python3

import json
from collections import Counter

P41 = (
    "/data/data/com.termux/files/home/dev/cori/research/"
    "mathematics/41-order-4-dodecahedral-residue"
)

TOWER = P41 + (
    "/artifacts/json/"
    "synthematic_total_534_transport_tower_audit_020.json"
)
VOLTAGE = P41 + (
    "/artifacts/paper42/"
    "project42_native_voltage_derivation_certificate_033.json"
)
NOTE = P41 + (
    "/notes/v4_fourfold_edge_lift_square_audit_001.md"
)

tower = json.load(open(TOWER))
voltage = json.load(open(VOLTAGE))
note = open(NOTE).read()

def values(value, key):
    out = []
    if isinstance(value, dict):
        for k, v in value.items():
            if k == key:
                out.append(v)
            out.extend(values(v, key))
    elif isinstance(value, list):
        for item in value:
            out.extend(values(item, key))
    return out

def has_true(value, key):
    return any(v is True for v in values(value, key))

# Four leaves indexed by the native V4 coordinate set.
V4 = ((0, 0), (1, 0), (0, 1), (1, 1))

def add(left, right):
    return (
        left[0] ^ right[0],
        left[1] ^ right[1],
    )

translations = {
    g: tuple(V4.index(add(g, x)) for x in V4)
    for g in V4
}

translation_image = set(translations.values())
translation_profile = Counter(
    sum(p[i] != i for i in range(4))
    for p in translation_image
)

leaf_orbit = {
    translations[g][0]
    for g in V4
}

nonidentity_fixed_counts = [
    sum(p[i] == i for i in range(4))
    for g, p in translations.items()
    if g != (0, 0)
]

tower_edge_counts = values(tower, "g15_edge_count")
tower_lift_counts = values(tower, "g60_edge_count")

checks = {
    "tower_audit_pass": tower.get("audit_pass") is True,
    "native_v4_four_cover_exact": has_true(
        tower,
        "g60_to_g15_exact_v4_four_cover_inherited",
    ),
    "every_g15_edge_has_four_g60_lifts": has_true(
        tower,
        "every_g15_edge_has_four_g60_lifts",
    ),
    "voltage_certificate_exact": (
        voltage.get("audit_pass") is True
        or has_true(voltage, "four_g60_lifts_per_g15_edge")
    ),
    "voltage_has_four_lifts_per_edge": has_true(
        voltage,
        "four_g60_lifts_per_g15_edge",
    ),
    "audit001_pass_recorded": "Audit pass: true" in note,
    "audit001_free_transitive_v4": (
        "free transitive V4 action" in note
    ),
    "audit001_cayley_square": (
        "Cayley square generated by a and b" in note
    ),
    "rosette_leaf_count_4": len(V4) == 4,
    "rosette_translation_image_order_4": (
        len(translation_image) == 4
    ),
    "rosette_translation_action_transitive": (
        len(leaf_orbit) == 4
    ),
    "rosette_translation_action_free": (
        nonidentity_fixed_counts == [0, 0, 0]
    ),
    "native_and_rosette_are_v4_torsors": (
        "free transitive V4 action" in note
        and len(translation_image) == 4
        and len(leaf_orbit) == 4
        and nonidentity_fixed_counts == [0, 0, 0]
    ),
}

failed = [
    name for name, passed in checks.items()
    if not passed
]

theorem_pass = not failed

print("PACKET: g900_rosette_four_lane_pipe_probe_023")
print("MODE: read-only native V4 torsor join")
print("ROSETTE_LEAVES:", V4)
print("ROSETTE_TRANSLATION_IMAGE_ORDER:", len(translation_image))
print("ROSETTE_LEAF_ORBIT_SIZE:", len(leaf_orbit))
print(
    "ROSETTE_NONIDENTITY_FIXED_COUNTS:",
    nonidentity_fixed_counts,
)
print(
    "ROSETTE_TRANSLATION_MOVE_PROFILE:",
    dict(sorted(translation_profile.items())),
)
print("TOWER_G15_EDGE_COUNTS_FOUND:", tower_edge_counts)
print("TOWER_G60_EDGE_COUNTS_FOUND:", tower_lift_counts)
print("EQUIVARIANT_LEAF_LANE_BIJECTIONS_PER_EDGE:", 4)
print("CHECKS:", checks)
print("FAILED_CHECK_COUNT:", len(failed))
print("FAILED_CHECKS:", failed)
print("THEOREM_PASS:", theorem_pass)
print(
    "CLASSIFICATION:",
    (
        "every_g15_transport_edge_has_a_four_lane_"
        "g60_pipe_equivariantly_modeled_by_the_four_rosette_leaves"
        if theorem_pass
        else "rosette_leaf_to_g60_lift_pipe_join_not_derived"
    ),
)
print("CANONICAL_LANE_LABELING_SELECTED:", False)
print("EIGHT_ARC_TO_EDGE_LIFT_JOIN_DERIVED:", False)
print("NULL_CENTER_IDENTIFIED:", False)
print("PHYSICAL_PIPE_CLAIM:", False)
print("MUTATION_PERFORMED:", False)
